#!/usr/bin/env bash

pseudoSrcFile=$1
#Escapes \# back to #
pseudoSrcFile="${pseudoSrcFile//\\#/#}"
objlib=$2
objname=$3

cmd=""
result=""

while read -r line; do
  line=$(echo "$line" | sed 's/\r//')
  if [[ $line = '/*'* ]]; then continue; fi
  if [[ $line = '' ]]; then continue; fi
  if [[ $line =~ [[:space:]]\+$ ]]; then
    linetmp=$(echo "${line%+}" | sed 's/\$/DOLLARESCAPE_/g' | sed 's/$/DOLLARESCAPE_/g')
    cmd="${cmd} ${linetmp}"
    continue

  fi
  line=$(echo "$line" | sed 's/\$/DOLLARESCAPE_/g')
  cmd+=$line
  if [ -n "$cmd" ]; then
    # Escape special characters for sed
    escaped_objname=$(printf '%s\n' "$objname" | sed 's/[&/\$]/\\&/g')
    result+=$(echo "$cmd" | sed 's/#/\\#/g' | sed "s/&O/$objlib/g" | sed "s/&N/$escaped_objname/g")
    result+="\n"
    cmd=""
  fi
done < <(grep "" "$pseudoSrcFile")

echo "$result"
